In [6]:
import cv2
import numpy as np
import os
import numpy as np
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA




In [7]:
train = []
test = []
train_t = []
test_t = []
train_img=[]
test_img=[]

for i in range(1,41):
    for j in range(1,11):
        img = plt.imread('att_faces/s{}/{}.pgm'.format(i,j))
        #print(img)
        if(j<=5):
            train.append(img)
            train_t.append(i)
        else:
            test.append(img,)
            test_t.append(i)
        
        #print(img)
#1D
for img in train:
    oneD=[]
    for x in range(img.shape[0]):
        for y in range(img.shape[1]):
            oneD.append(img[x][y])
    train_img.append(oneD)
for img in test:
    oneD=[]
    for x in range(img.shape[0]):
        for y in range(img.shape[1]):
            oneD.append(img[x][y])
    test_img.append(oneD)
#轉array

train_img = np.array(train_img)
test_img = np.array(test_img)
test_t = np.array(test_t)
train_t = np.array(train_t)


In [8]:
#GridSearchCV參數
param_grid = {'C': [1e3, 5e3, 1e4, 5e4, 1e5],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.1], }

#PCA
pcaClf = GridSearchCV(SVC(kernel='linear', class_weight='balanced'),param_grid)
ldaClf = GridSearchCV(SVC(kernel='linear', class_weight='balanced'),param_grid)

for i in range(10,51,10):
    print('\n'+str(i)+'\n')
    
    mPCA = PCA(n_components=i).fit(train_img)
    pca_tr = mPCA.transform(train_img)
    pca_te = mPCA.transform(test_img)
    
    pca_pre = pcaClf.fit(pca_tr,train_t)
    pca_t_p = pca_pre.predict(pca_te)
    
    pca_cm = confusion_matrix(test_t,pca_t_p)
    #acc
    #pca_acc = accuracy_score(pca_t_p,test_t)
    pca_report = classification_report(test_t,pca_t_p)
   
    print('--------------------------------------------------------------------------------------')
    print("\nPCA confusion matrix")
    print(pca_cm)
    print('\nPCA report')
    print(pca_report)
    print('--------------------------------------------------------------------------------------')

#LDA 
    if(i<40):
        mLDA = LDA(n_components = i).fit(pca_tr,train_t)
        lda_tr = mLDA.transform(pca_tr)
        lda_te = mLDA.transform(pca_te)
        
        lda_pre = ldaClf.fit(lda_tr, train_t)
        lda_t_p = lda_pre.predict(lda_te)
        
        lda_cm = confusion_matrix(test_t,lda_t_p)
        lda_report = classification_report(test_t,lda_t_p)
        
        print("\nLDA confusion matrix")
        print(lda_cm)
        print('\nLDA report')
        print(lda_report)
        print('--------------------------------------------------------------------------------------')
        


10

--------------------------------------------------------------------------------------

PCA confusion matrix
[[4 0 0 ... 0 0 0]
 [0 5 0 ... 0 0 0]
 [0 0 5 ... 0 0 0]
 ...
 [0 0 0 ... 5 0 0]
 [0 0 0 ... 0 5 0]
 [0 0 0 ... 0 0 5]]

PCA report
              precision    recall  f1-score   support

           1       1.00      0.80      0.89         5
           2       0.62      1.00      0.77         5
           3       1.00      1.00      1.00         5
           4       0.83      1.00      0.91         5
           5       1.00      0.80      0.89         5
           6       1.00      1.00      1.00         5
           7       1.00      1.00      1.00         5
           8       1.00      1.00      1.00         5
           9       1.00      1.00      1.00         5
          10       1.00      0.80      0.89         5
          11       0.71      1.00      0.83         5
          12       1.00      1.00      1.00         5
          13       1.00      1.00      1.00        

C:\Users\claire\anaconda3\envs\patterrnrecognition\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\claire\anaconda3\envs\patterrnrecognition\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\claire\anaconda3\envs\patterrnrecognition\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m

--------------------------------------------------------------------------------------

PCA confusion matrix
[[5 0 0 ... 0 0 0]
 [0 5 0 ... 0 0 0]
 [0 0 5 ... 0 0 0]
 ...
 [0 0 0 ... 5 0 0]
 [0 0 0 ... 0 5 0]
 [0 0 0 ... 0 0 5]]

PCA report
              precision    recall  f1-score   support

           1       0.83      1.00      0.91         5
           2       0.71      1.00      0.83         5
           3       1.00      1.00      1.00         5
           4       1.00      1.00      1.00         5
           5       1.00      0.80      0.89         5
           6       1.00      1.00      1.00         5
           7       1.00      1.00      1.00         5
           8       0.83      1.00      0.91         5
           9       1.00      1.00      1.00         5
          10       1.00      0.80      0.89         5
          11       0.71      1.00      0.83         5
          12       1.00      1.00      1.00         5
          13       1.00      1.00      1.00         5
  

--------------------------------------------------------------------------------------

PCA confusion matrix
[[5 0 0 ... 0 0 0]
 [0 5 0 ... 0 0 0]
 [0 0 5 ... 0 0 0]
 ...
 [0 0 0 ... 5 0 0]
 [0 0 0 ... 0 5 0]
 [0 0 0 ... 0 0 5]]

PCA report
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         5
           2       1.00      1.00      1.00         5
           3       1.00      1.00      1.00         5
           4       1.00      1.00      1.00         5
           5       1.00      0.80      0.89         5
           6       1.00      1.00      1.00         5
           7       1.00      1.00      1.00         5
           8       0.83      1.00      0.91         5
           9       1.00      1.00      1.00         5
          10       1.00      0.80      0.89         5
          11       0.71      1.00      0.83         5
          12       1.00      1.00      1.00         5
          13       1.00      1.00      1.00         5
  